apiVersion: v2
name: onecx-hello-world-bff
version: 0.0.0
appVersion: 0.0.0
description: Onecx hello world bff
keywords:
  - iam
  - parameters
sources:
  - https://github.com/onecx/onecx-hello-world-bff
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.41.0
    repository: oci://ghcr.io/onecx/charts